version: "3"
services:
  bot-web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - qdrant
  qdrant:
    image: qdrant/qdrant
    environment:
      - QDRANT__STORAGE__STORAGE_PATH=/var/lib/qdrant
    volumes:
      - qdrant_data:/var/lib/qdrant
    ports:
      - "6333:6333"

volumes:
  qdrant_data:
